### ISSUE TITLE
Unable to set Theme using a Style

### ISSUE THREAD

**Issue by tylercamp** [BinToss/GroupBox.Avalonia#57]
This might be a general Avalonia question, but I'm trying to set the theme for all GroupBoxes in a control using a Style, and I'm getting a "Static resource not found" error with:

```xaml
	<UserControl.Styles>
		<Style Selector="ctrl|GroupBox">
			<Setter Property="Theme" Value="{StaticResource GroupBoxClassic}" />
		</Style>
	</UserControl.Styles>
```

**Comment by BinToss** [comment]
That's...odd.
I'll have to set up another project alongside the sample project to troubleshoot this.

**Comment by BinToss** [comment]
Oh, disregard my previous statement!
Assuming you want to apply the Classic theme to all GroupBox instances under your User control, you will want to create a merged resource dictionary containing the `GroupBoxClassic` resource.


Past me was smart enough to use the exact syntax needed in the GroupBox Control's axaml.
https://github.com/BinToss/GroupBox.Avalonia/blob/b32498a5684ec833c96d0ea7548524a591ca5d75/GroupBox.Avalonia/Controls/GroupBox.axaml#L10-L11
